### ISSUE TITLE
precision lose when using latitude and longitude

### ISSUE THREAD

**Issue by carlin314** [chris48s/geometry-to-spatialite#29]
The correct line is red, while converted spatilite is purple, what can be the reason?

I hope you can help me to figure it out

![image](https://user-images.githubusercontent.com/16414165/83860114-6ceecb80-a751-11ea-988d-95f93ae1ef99.png)

My test geojson
[1591263744_bak.geojson.tar.gz](https://github.com/chris48s/geometry-to-spatialite/files/4735132/1591263744_bak.geojson.tar.gz)

**Comment by carlin314** [comment]
I found it is cause by geojson library used by you, its defualt precision is 6

**Comment by chris48s** [comment]
You are right that this behaviour is caused by a third-party library. There's a long thread about this at https://github.com/jazzband/geojson/issues/135 and I understand why they've made this decision ( https://tools.ietf.org/html/rfc7946#section-11.2 ) but I feel like the implementation is a bit unhelpful and the issue is going nowhere.

In this library, using `geojson` was helpful for a bit of validation on load, but beyond that its not really buying me a lot over a straight `json.load()`. Given it introduces a problem here and there isn't really a good workaround, I've just published [version 0.3.1](https://pypi.org/project/geometry-to-spatialite/0.3.1/) which drops the dependency on `geojson` and removes this rounding issue.

Give it a try.

**Comment by carlin314** [comment]
It work fine, thx for your work
